import os
import unittest
from bioinformatics_tools import (run_genscan, GenomicElement,
                                  DNASequence, RNASequence, AminoAcidSequence)
from bio_files_processor import (select_genes_from_gbk_to_fasta,
                                 convert_multiline_fasta_to_oneline,
                                 change_fasta_start_pos)


class TestClasses(unittest.TestCase):
    def test_DNASequence(self):
        sequence = 'ATGCCGTGCA'
        dna = DNASequence(sequence)
        alphabet = {'A', 'T', 'C', 'G'}

        self.assertEqual(dna.sequence, sequence)
        self.assertEqual(dna.alphabet, alphabet)
        self.assertEqual(dna.transcribe().sequence, 'AUGCCGUGCA')
        self.assertEqual(dna.complement().sequence, 'TACGGCACGT')
        self.assertEqual(dna.gc_content(), 0.6)

    def test_RNASequence(self):
        sequence = 'AUGCCGUGCA'
        rna = RNASequence(sequence)
        alphabet = {'A', 'U', 'C', 'G'}

        self.assertEqual(rna.sequence, sequence)
        self.assertEqual(rna.alphabet, alphabet)

    def test_AminoAcidSequence(self):
        sequence = 'DYEVTFTEDKINAL'
        peptide = AminoAcidSequence(sequence)
        alphabet = set("ACDEFGHIKLMNPQRSTVWY")

        self.assertEqual(peptide.sequence, sequence)
        self.assertEqual(peptide.alphabet, alphabet)
        self.assertEqual(peptide.molecular_weight(), 1.9)


class TestErrorRaising(unittest.TestCase):
    def test_select_genes_from_gbk_to_fasta_error(self):
        with self.assertRaises(ValueError):
            select_genes_from_gbk_to_fasta('./data/example_gbk.gbk', 'HIF1AN')


class TestGenscan(unittest.TestCase):
    def test_run_genscan(self):
        sequence = 'CTTTCTGTCCCGCCCTTCCTCTGACTGTGTCTTGATTTCCTATTCTGAGAGGCTATTGCTCAGCGGTTTC CGTGGCAACAGTAAAGCGTGGGAATTACAGATAAATTAAAACTGTGGAACCCCTTTCCTCGGCTGCCGCC AAGGTGTTCGGTCCTTCCGAGGAAGCTAAGGCCGCGTTGGGGTGAGACCCTCACTTCATCCGGTGAGTAG CACCGCGTCCGGCAGCCCCAGCCCCACACTCGCCCGCGCTATGGCCTCCGTCTCCCAGCTTGCCTGCATC TACTCTGCCCTCATTCTGCAGGACTATGAGGTGACCTTTACGGAGGATAAGATCAATGCCCTTATTAAAG CAGCCAGTGTAAATATTGAAACTTTTTGGCCTGGCTTGTTTGCAAAGGTCCTGGCCAACGTCAACATTGG GAGCCACATCTGCAGTGTAGAGGGGGGGAAAAAAACGTGACTGCGCGTCGTGAGCTCGCTGAGACGTTCT GGACGGGGGACAGGCCGTGGGGTTTCTCAGATAACTGGGCCCCTGGGCTCAGGAGGCCTGCACCCTCTGC TCTGGGTTAAGGTAGAAGAGCCCCGGGAAAGGGACAGGGGCCCAAGGGATGCTCCGGGGGACGGGCGGGG GAAAGTGAATTTCCGAAGCTAGGCAGATGGGTATTCTTATGCGAGGGGCGGGGGCGGAACCTGAGAGGCA TAAGGCGTTGTGAACCCCCCGGGGAAGGGGGCAGTTTGTAGGTCTCGAGGGAAGCACTAAGGATCAGGTT GGGGGCACAGTGTGTCCGAGGAGGAATCCTCCTGATAGGAACTGGAATGTGCCTTGAAGGGGACACCATG TGTATAAGAACATCAGCTGGTCGCCGGGGATGGTGGCTTACGCCTGTATTCCTAGCACTTTGGGAGGCCA AGGCGGATGGATCACGAGGTCAGGAGTTCGAGACCAGCCTGACCATCGTGGTGAAACCCCGTCTCTACTA AAAATACAAAAATTAGCCGGGCGTGGTGGCGCGCGCCAGCTACTCAGGAGCTGAGGCAGGAGAATCGCTT GAACCCAGGAGGCGGAGGTTGCAGTGAGCCGAGATCGCGCCATTGCACTCCAGCCTGGGTGGCAGAACGA CACTCCGTCTCAAAAACAAACAAAGAAATAAACACCGGCTGGTATATATGAGAAGATGGGCCCTTGCGGA AGAAGAAGTGCCAGGAATATGTCTGGGAAGGGGAGGAGACAGGATTTTGTGGGAGGGAGAACTTAAGAAC TGGATCCATTTGTGCTATTGAGAAAGCGCAAGAGGGAAGTAGAGGAGCGTCAGTAGTAACAGATGCTGCC GGCAGGGATGTGCTTGAGGGGGATCCTGAGATGAGAGTGGGTCGCTGGGAAAGGCTAGGGGCAGGGAGGC CTTGATTGGTGTTGGTTTGGTCGTTGTTGATTTTGGTTTTATGCAAGAAAAAGAAAACAGCCAGAAGCAT TGGAGAAAGCTCACCACTTACCCGGTCAGTCACTCCCCTGTAGCTTTCTCTTTCTTGGAGAAAGGAAAAG ACCCAAAGGGTTGGAAGCAATATGTGAAAAAATACAGAATTTATATTGTCTAATTACAAAAAGCAACTTC TAGAACCTTTAAAGGATTTTGTATTATTCTAAAACCTTCCAAATCTTAAATTTACCTTATTTTATTTTAT TTATTTTTGAGACGGAGCTTCGCTCTTGTTGCCCAGGCTGGAGTGTAATGGCGTGATTTGGGCTCACCGC AACCTCTGACTCGTGGGTTCAAGCGATTCTCCTGCCTCAGCTCCCGAGTAGCTGGGATTACACGCATGCA CCACCATGCCTGGCTCATTTTTTTGTATTTTTAGTAGAAACGAGGTTTCTCCGTATTGGTCAGGCTGGTC TTGAACTCCCGACCTCAGGTCATCCGCCCGCCTCGGCCTCCCTAAGTGCTGTGATTACAGGCGTGAGCCA CCACGCCCAGCCCAATTTACCTTATTTTAAAATGATAAAATGAAGTTGTCATTTTTCTAAACCTTTTTAA AAGATACATGTTTTTCTAATGTGTTAAAGTTCATTGGAACAGAAAGAGATAGATTTATCTGCTGTTTGCG TTGAAGAAGTACAAAATGTCCTTAATGCTATGCAGAAAATCTTACAGTGTCCAATCTGGTAAGTCACCAG AAGAGGGTATTAATTTGGGATTCCTATATGATTATCTCCTATGCAAATGAACAGAATTGACCTTACATAG AAGGGAGGAAAAGACATGTCTAATAAGATTAGGCTATTGTAATTGCTGATTTTCTTAACTGAAGAACTTT AAAAGTATAGAAAATGAATCCTTGTTCTCCATCCACTCTGCCTCTCCCACTCCTCTCCTCTTCAACACAA ATCCTGTGGTCCCTGAAAGACAGGGACCCTGTCTTGATTGGTTCTGCACTGGGGCAGGAATCTAGTTTAG ATTAACTGGCATTTTGGTTTTCTTCTAGCTCTAAAACCAGCTCCATCACTTGAAATGGCAAAATAAATCA TGAATGAGGCCGGGGGCTGTGGCTCACACCTGTAATCCCAGCACTCTGGGGGGCCGAGGCAGGCAGATCA CGAGGTCAGGAGATCGAGACCATCCTGGCTAACATGGTGTAAGGGAGGAGACCACCCCTCATATTGTCTT ATGCCCAATTTCTGCCTCCAAAGAAAGAAAAAGTAAAAACTAAAGGGCAGAAATGACATCCACAAGCAGA CACCCCAGGTGCCACACCCTGGGCCTGGTAGTTAAAAATCAACCCCTGACCTGATTGGTATGTTATCTAT AGATTACAGACATTGTATAGAAAAGCACTGTGACAATGCCTTTCCTGTTTTGTTCCGATCTAGTTACTGG TGCATGCAGCCCCCAGTCACGTACCCCCTGCTTGCTCAATTGATCACGACCCTCTCACGTGCACCCCCTT AGAGTTGTGAGCCCTTAAAAGGGACAGGAATTGCTCACTCGGGGAGCTTGGCTCTTGAGACCGGAGTCTT GCCGATGCCCCTGGCCTAATAAACCCCTTCCTTCTTTAACTCGGTGTCTGATAAGTTTTGTCTGCAGCTC GATTTCTTGGTTCCCTGACTGGGAAGCGAGGTGAATGGCGGATGGTCAAGGCAGCTCCTTAGGCGGCTTA AACCTGCCCTGTGGAACATCCCTGCAGGGGACTCCAACCAGCCCGAGCAACACGGATCCTGAGGGCGCTC CTGGTTAGGCATTTGCCCCACTGGGACGCCTCGCCAGAGCACTGTATGGCAGGCCCCCATGGAGGATCAA CGCAGTGGCTGAACACCGGGAAGGAACGGGCACTTGGAGTCTGGACATCTAAAACTTGGTAAGAGTAGTC TTTGAAACTTGCCCACTCCATTTGAGTGGAAGCATGGCCTGATCACCCATGGCGTGCCTTTATTGGCACT TTGGTTTTGGTTTGAATTGCTTGACAGGATTGGTCTTGGGAACTTGCCTACTCCATTTGAGTGGAAGTGT GGCCTGATCACCCATGGTGTGCCTCTCCTGGCACTTTGGTTTTTATTTTTGACTTGACTTGGATTGCTTG ATACTTTGGTTTTGGTTTTGACCTGGCTTGGATTTCTGGATACTCTGATTTTGGTTTGGTGCAAACTGCA AAACTGTGTGTGCGCCCTTTTTACCGGTTCTTTGTTTTGTGGTGTGTTTGTGGTGTGAGCGTGGTGTTTT GTCTTGAAGAAGCATAGGTCAGGCACGAATAAGCCCACCCCACTAGGAACTATGTTGACAAATTTCAAAA AAGAATCTGAGGGAGACTATGGAGTGCTATGACACCAGGAAAACTTAAAACTTTGTGTAAGATAGACTGG CCAGCATTAGAGGTAGGTTGGCCATTAGAAGGAAGCCTGGACAGGTCCCTTGTTTCAAAGGTATGGCACA AGGTAACCTATAAGCCAAGGAACCCAGACCAGTTCCCTTACAGAGACACTTGATTAGAGCTGGTTTTAGA CCCCCCACCCCCAACACATAGTGGTTGAGAGAACAGCAGCATAAGTGGCTGGCAGAGGCAAGGAAAGACC AGCAGAGAGAGAGAAAGGAAAGAGACAGAGAGGAAAAGAGGAAAAGAGAGAGAGGAAGAGACAGGAAGAG ACAGACAGAGAGTCAAGGATAGAGAGAGAGAGAGAGAGAGAGACACACACACACACACACACAGAGAGAG AGGAAGAGGCAGAGGCAAAAGGAAAGTCAAAGAGAGAGACAAAGTCAAAGAGAGAAAGAAAGAGAGAAAG AGAGAGAGATACAAAGTTAAGAAAAAAAAGCCATCTATACCAATTCTAATTTAGACAAAACAAGGTCTTA TTAATAGCAAAGGATAATTAAAATCCCAAACTTAGAAGGTTTTCTTTTTATTATTATTATTATTATACTT TAAGTTTTAGGGTACATGTGCACAACATGCATTTTTTTAAAATTTTTTTTAAAGGTTTTCAACTAAAGTT TGCTAAAAGTTAACAGTGTAACATGTATATAGTAACTTATATTCTTGTGGCCTAGTCCACAAGACACAAA AAAGGTTCGCTTTGGAAAAGAATGGTTATCATCTTCGAAAAAAAAAAGGAAAAAAAGGGGGGGCGGAATT TATATAAAAAGAGTATTATATGGTAAATTCTTGTCCTGAAACAAATTAACTGGTTGTTTAAAGAAATAAA TATTTGTAATAAGTCAGAAAGTTGAGGCATATCGAAGAATTGTCTGCGAAAGTCACGAAAGAGAAAAATG TTATAAAAAAATTTATGCAAAAAATGTTGTATAATTTAAAAGTAACTAGGCCTCCTGAATGTAAAACTGT TGAAAAAAAAAACAGTTTATATGCAAGGTGTATAAGAAAAGTAAAATATATCTTTGGTAAAAGAATTGTA AGGAGGCATAAGGATGTACATTTTCACCTACATTAAAAGGTTAAAAATAATTATTGTTTTGAAGATTTAA GCAAGTTTCAAAATGTTAATTGTAAAGAAAATTCTGTGTGTAAACATATTAGCTAAAGTTAAAGAAGTAT CATCCAGTTTTTCTGTGAACTGGACATTAAAGTAAAAGCATAACAGGTTTTTTCTTAAAGCACCAACCTG CTCTTTTGCAAAAATTATAAAGGGTTAAAAAGAATCTATAAAATCTTACCTTATGGTCAAACATTAACAA TTAGATACATATGTCTACAAGGTTTTATTAAAATTAAGTTTAATATTAATAACACACTAATATAAAGATA AAATTTAGCTTATCTGGTATAAAAATCATACGAGAAGCACTGTTAAATGTAAAATGGTATTTGGCTTTCT TTGGTTTAAAAACTAATAAAAATAGGTGCTAAAGGAAATTTCTCAGGAAAAAGGCACTAAGGACTATAAA GTCCACTGCCAAGGTCCCCACATTTAAAACAAAAGGTCAGTTCCTTAGAATTATATGCTTGGTTTATTTT CCACTTTCCTTTCTCTCAAAAACTAAAAGTCTTTTAGCACATGTACCACCCCTAGAATTTCTAGTAAACC AGCACCAGCCTGAAGATCACATTCTCATCGAAAGGTGGAAAGAAGAAAAACTCGAGCCAGCCTGGAAGGA CCCTACCTTGTGTTGCTAACCACCAAGACTGCTGTTCGTACAGCAAAAAAGGATGGACTCGTCACACCAG AATCAAGAAAGTGCCACCCCCTCCAGAGTCATGGGCCACAGTCCCAGAGGAAAACCCTGCCAAACTAAAG CTACGAAAAATCTCTTTTCATCTATTCTATTACTCTTCTTTCTTTCCTCGTGCTATTGCTGACCATCTAG TTATTAACATAACCAAGTCAATTTCACCTCAAACTATTGCATTTAATGCTTGCCTTGTTATACCCTGTGG GGACTTGCCAAGTCAAAGACAGCTCTCTACTTCAGAAAAGTACTTCTGTCCCTCCTGACTCTCCTCAGAC TGGACATTAGTAAACTAGGACCATTTAATCCAGGGAGATTTCGATAAAGACCCCAGTGCCAACCAGGAGT CTTGTCCCCTGATGTAGAGTTTTTATGCCGTAGTTGGTCCAACGTTCTGTGGACCACTAAAGAGCAAGAA TGGACTGCCCCAACCAGTTTTTGTAATTTCCTAAAACCATACATTCGTTTTACTAGAGGATCATAGAAGT TAAAGAGTTAAAACAAACTTTACCAATGAAGACAGGATACCAAGATGCAAATGCCTGGTTAAAATGCATC AAATATTCCATCTGCACGTTAAACAAAAGCAATTGTTATGCTTGTGCACATGGCAGGCCAGAGGCCCAGA TTGTCCCCTTTCCACTAAGGTGGTCCTCCAGTCGACCAGATGTGGGCTGCCTGGTAGCTCTTTTCCAGGA TTCTACAGCCTGTATTAATAAGTCATGCCAAGCTCTCTCTGCTATATCCCAAAGTCCAGCACCCTGCGGG TCAGCCCCCGAGGGCCATCCATCCTCCATCTCCCAACACTAAGTTCACTTCATGTCTCTCACAACAGGGA GGAAACTTAGCGTTCCTTGGAGACCTGAAAGGATGCAGTTAGCTTAAGAATTTTCAAGAGCTTATCAATC AGTCAGCCCTTGTTCATCCCCGAGCAGATGTGTGGTGGTATTGTGGTGGACCTTTACTGGGCACTCTGCC AAATAACTGGAGTGGCACTTGTACTTTAGTCCAATTGGCTATCCCTTTCACCCTGGCATTTCATCAACCA GAAGGAAAAAAAGAAAGACATTGTAAAGCGAGAGAAGCCCCTTATGGGTCTTTCGACTCTCATGTCTATT TAGATGCAATTGGAGTCCCACGAAGAATACCAGATCAATTTAAAGCTTGAAATCAAATAGCTGCAGGATT TAAGTCAATATTTTAGTGGGTGACAGTTAATAAAAATGTAGATTAGATAAACTACATCTATTACAACCAA CAACAACGAGGTTTTCATGAGTTAAAAGAAAACCTCATGTTGGTCCCAGCCCTGAGGCTACCTGACCTGA CAAAACTCTTTACACTCTATGTGTCAGAAAGAGAAAAAATGGCAGTTGGAGTTTTAACCCATACTGTGAG GCCCTGGCCAAGGCCAGTGGCCTATCTCTCAAAACAACTAGACAGGATTTCCAAAGGCTGGCCCCCAGGT CTAAGGGCCCTAGCAGCAACAGCCCTGTTAGCACAAGAAGCAGATAAACTAACCCTTAGGAAAACCTGAA TATAAAGGCCCCCCATGCTGTGGTAACTTTAATGACTACCAAAGGACCTCATTGGTTACAAATGCTAGAT TAACCAAGTACCAAAGCTTGCTATGTGAAAATCCCCACATAACCACTGAAGTTTGCAACACCCTAAACCC CACCACCTTGCTCCTGGTATCAGAGAGCCTAGTTGAACATACTGTGTAGAGGTGTTGGACTCAGTTTATT CTAGCAGGCCCAACCTCCGAGACTATCCTTAAACATCAGTAGACTGTGAGGGGTACGTGGACGGGAGTAG CTTCGCCAACCCCTGCAAAGTGACTCTGAAGAAGACGACAAGCTCTGCTCCAGTCACACCCAGAAGCTGA CTGGTCCACGCACGGCCGAAGCATGAGAAAACTCATTGCGGAACTCATTTTCCTTAAAATTTGGACTTTT ACAGTAAGGACTTCAACTGACCTTCCTCAGACTGAGGACTGTTCCAGTGTATACATCAAGTCACTGAGGT AGGACAAAAGGTTGCTACAGTCCTATTATTTTATGGTTATTATAAGTGTACTGGAACTCTAAAAATAACT TGTTTGTATAATGTTATTCTGTACAAGGTATGTAGCCCAGGAAGTGACCAACCTGATGTGTGTTATGACC CATCTGAGCCTCCCATGACCACGGTTTTTAAAATAAGATTAAGGACTGAGGACTGGTGGGGGCTCATAAA TGATATGAGTAAAGTGTTAGCCAAAACAGAAGAAAAAGGGGTGCCCAAACAAGTCACCTTAAAATTTGAT GCCTGTGCTGTCATTAATAGTAATAAGTTAGGAATAAAGTGTGGTTCTCTTAATTAGAAAAGAGGCTATA TGGCAGAAAATAAGTACATCTGTCATAAATTAGGACTGTGTGGAAATAAATGTAAATACTGGTCTTGTGT CATTTAGGCCACTTGGATTTAAAAAAAATGAAAAGGATCCAGTCCACCTTCAGAAAGGAAAAAAATGGCC CTTCCTGTGCTAAGGGACAATGTAACCCCTTAGAGCTAGTAATAACCAATCCCCTTGATCCTCGCTGGAA AAAAGAGTAGCGTGTGACCTTAGGAATCAATGGGGCTGGACTGAATCCCCGAGTAAATATCTTGGTTCGA GGAGAAGTTTACAAATGCTCTCTTGAGCCAGTGTTTCAAACTTTCTATGATGAACTAAATGTGCCAATAA CAGAATTTCCAGGAAAAACAAGAAATTTGTTTTTGCAATTAGCCGAGCATGTAGCCCAGTCTCTCACTGT CACTTCATGTTATGTATGTGGAGGAACTGTAATAGCAGATCAATGGCCATGGGAAGCCCGAGAATTAGTA CCTACAGACCCAGTTCCTGATGAATTCCCAGCTCAAAAGAATCACCCTGATAATTTCTGGGTCCTAAAAG CCTCAATCATTAGACAATACTATATAGCAAGAGTGGAGAAGGACTTCACCCTTCCTGTAGGAAGACTACA TGGTGGAGTTCAAACCACACAGAGAAAAATCCATTCAGTAAATTTCCAAAGTTGCAGACCGTTTAGGCCC ACCCAGAATCCCACCGGGACTGGACAGCCCCCACTGGGCTATACTGGATATGTGGACATAGAGCCTACAC TAAGCTGCCTGACAAGTAGTTGTGTTATTGGCACTATTAAACCATCTTTCTTCCTACTGTCCATAAAAAC AGGAGAACTCCTGGGCTTCCCTGTCTATGCTTCCCGTGAAAAGCATAGCTATAAGAAATTGAAACAATGA TAAATGGCCCCCTGAGAGAATCATACAGTATTATGGGCCTGCTACTTAGGCACAAGATGGCTCGTGGGGA TACCGGATCCCCATTTATATGATCAACTGAATCATACGGTTACAAGCTGTCTTAAAAATAATCACTGCAA CCGGCAGAGCCTTGACTATTCTGGCCCAGCAAGAAACTCAGATGAGAAATGCTATCTATCAAAATAGATT AGCTCTCGACTACTTGCTAGCAGCTGAAGGAGAGGTCTGTAGGAAATTTAACCTTACTAATTGCTGCCTA CACATAGATAACCAAGGGCAAGTAGTTGAAGACATAGTTAGAGATATGACAAAAGTGGCACATGTGCCCG TGCAAGTGTGGCATGGATTTGATCCTGGGGCCATGTTTAGAAAATGGTTCCCAGCGCTAGGAGGATTTAA AACTCTTATAATAAGAGTTATAATAGTAATAGGAACCTACTTACTGCTCCCTCGTTTGCTACCTGTACTT CTTCAAATGATAAAAAGCTTCATCGCTACCTTAGTATACCAAAATGCATCAGCACAAGTGTACTATATAA ATCACTATTGATCTGTCTAGCAAGAAGACATGGGTAGTAAACATGAAACAACTCCTGCTATTGAGTGAGA GTCTCAAAGTGGGGGAATAAGGGAGGAGACCACCCCTCATATTGTCTTATGCCCAATTTCTGCCTCCAAA GAAAGAAAAAGTAAAAACTAAAAGGCAGAAATGAAATCCACAAGCAGACAGCCCGGGCGCCACACCCTGG GACTGGTAGTTGAAAATCAATCCCGGACCTAATCGGTTATGTTATCTATAGATTACAGACATTGTATAGA AAAGCATTGTGAAAATCTCATTCCTGTTTTGTTCCAATCTAATTACTGGTGCGTGCAGCCCCCAGTCACG TACCCACGTACCTCCTGCTTGCTCAATCGATCACGACCCTCTCACGCACACCCCCTTAGACTTGTGAGTC CTTAAAAGGGACAGGAATTGCTCACTCGGGGCGGGGGCTCGGCTCTTGAGACAGGAGTCTTGCTGATGCC TCCGGCCTAATAAACCCCTTCCTTCTTTAACTCGGTGTCTGAGGAGTTTTGTCTGCAGCTCGTCCTGCTA CAGGTGAAACCCCATCTCTACTAAAAAAATACAAAAAAATTAGCCAGGTGTGGTGGCGGGTGCCTGTAGT CCCAGCTGCTTGGGAGGCTGAGGCAGGAGAATGGTGTGAGCCTGGGAGGCAGAGCTTGCAGTGAGCCGAG ATCATGCCACTGCACTCCAGCCTGGGCAACAGAGTAAGACTCCGTCTCAAAAAAAAAAAAAAAAATCATG GATGGTTGGTGTCATGGAGGGGATAGGTCTTTGGAAGAACCTTCCTCTGAAGCTGGCTCTGTACATTTAA ATAAGAATACTGCAAATCATCAAAGCCTTTAGCAAGTCTGACTCTTGGAGTGAGCCTTTGTTTTTCTTCA TTTATAAAAGGAAAAGGGGACTGTACTGTTCACATTTATTTATTTTTTTATTTTTTTAATTGATCATTCT TGGGTGTTTCTCCCAGAGGGGGATTTGGCAGGGTCATAGGACAATAGTGGAGGGAAGGTCAGCAGATAAA CAAGTGAACAAAGGTCTCTGGTTTTCCTAGGCAGAGGACCCTGCGGCCTTCCGCAGTGTTTGTGTCCCTG GGTACTTGAGATTAGGGAGTGGTGATGACTCTTAACGAGCATGCTGCCTTCAAGTATCTGTGATGTGAGG AGCGCCTCTGCCCGGCCGCGACCCCGTCTGGGAGGTGAGGAGCATCTCTGCCCGGCCGCCCCGTCTGAGA AGTGAGGAGACCCTCTACCTGGCAACCGCCCCGTCTGAGAAGTGAGGAGCCCCTCCGCCTGGCAGCCACC CCGTCTGGGAAGTGAGGAGCGTCTCAGCCCGGCAGCCACCCCGTCCGGGAGGGAGGTGGGGGTCAGCCCC CGCCAGGCCAGCCGCCCCGTCCGGGAGGGAGGTGGGGGTCAGCCCCTGCCAGGCCAGCCGCCCCGTCCCG GAGGGAGGTGGGGGGGTCAGCCCCCTGCCCGGCCACATTTTGTTTTTGAATCGAGGTATAATTTACATAC AGTGAAATGCAGAGGTTTTTTTATACAGGATCTCTGTCGAGAGGCTGGAGTGCAGTGGTGCTATCACAGC TCACTGCAGCCTCAACCTCGCCAGGCTCAAGCGATCCTCCCACCTCAGCCTCCAGAGTAGCAGGGACTAC AGGTGTGCATCACCATGCCCAGCTAATTTGTGTGTGTGTGTTTGTGTGTGTGTTTGTAGATATAGGGTTT TGCCATGTTGGCCACGCTGGTCTCAAACTCCTGACCTCAAGTGATCTACCCACCTTGGCCTCTCAAAGTG CTGGGATTACAGGTATGAGCCTCTGCACCCAGCCATGGTCTGAAAATCTTGATTGAAATACCACCTTTTC ATTTCCAGACACCGCTATTTAAAGTTACAACACCCTCAAGACACACTTTATCCTCCATTCCTGCTGCTTC TCCATAACACTTATTACTAGCTGACCTTCTATGTAATGTATCTATCCTTTATCTCTAGTCCCACAGAATG TAAACTCCAGGGCAGCAGAGATTTTTGTTTCGTTTATGTACATCTGTATATTCAGTAGTTAAAACAGTAC TTGGGACCTAGTTGCCACTCAATAAACATTTGTTGAATAAATTAAATAATAAACTACATTAGTTCTTCAA TTAATTTTTTAAAATATGGTGGTTAATAGTGAGTAACATTCAAAAAATAAGTTGAAAATTTATACCTATT GCCTCTTACCCACAATAAAAAAGGGTAAATTCAAGGAAATTTTCTTTTGTGCTTTATGAAAGTTGTTTTTCATATTTGGAGTCATGTCAATCAGATTAAGGAAAATGCAAGTTGTGTTTTCAGAGAGATACAAGATTTATAAATAACCATCCTCTCCCTTGCCCTTCAACATTTTAGCTAAACAAAAACAAGAGGAAAACAAGATTTACAATTTATCAATTCATTGAAAATCAGAGCCAGAGAAGCAGGAAATGACATTGTAGGAAAAAACTGCTTTTGAAAAAGCACAACTTACTCATGACAATCAGAGTGATCAAAAAAATCCTCAATAGTGTGGCATTTGGATCCATTTATCATTACATTTCCATGGGACAGAGTCATAAAAATAGGATGTTCTTTCTCATTATGGCAAATTAAACCATCAATTAAAAACTCAGATACATAAAAATTAAAGATGTAAGAATGAAAGTTAATGCTAAATTTTTATTTTCAGTCAACTATTGTATGTTTTCTAGCTTTTCATTGCTTTTTTCCTATTTTCTGTTAGATTAATATTTTTT'
        output = run_genscan(sequence=sequence)
        asserted_cds_list = ['DYEVTFTEDKINALIKAASVNIETFWPGLFAKVLANVNIGSHICS'
                             'VEGGKKT', 'WSTERWTNYGIKTLHQGTRLLVGTGVFIEISLD']
        asserted_exon_list = [GenomicElement
                              (number=1, start=302, end=460),
                              GenomicElement
                              (number=1, start=6076, end=5975)]
        asserted_intron_list = [GenomicElement
                                (number=1, start=460, end=6076)]
        self.assertEqual(output.cds_list, asserted_cds_list)
        self.assertEqual(output.exon_list, asserted_exon_list)
        self.assertEqual(output.intron_list, asserted_intron_list)


class TestWriteToFile(unittest.TestCase):
    def test_convert_multiline_fasta_to_oneline(self):
        test_file_path = './data/BRCA1_one_line_test.fasta'
        convert_multiline_fasta_to_oneline('./data/BRCA1.fasta',
                                           'BRCA1_one_line.fasta')
        output_file_path = './BRCA1_one_line.fasta'

        self.assertTrue(os.path.exists(output_file_path))

        with open(output_file_path, 'r') as output_file:
            with open(test_file_path, 'r') as test_file:
                written_content = output_file.read()
                test_content = test_file.read()
                self.assertEqual(written_content, test_content)

    def test_change_fasta_start_pos(self):
        test_file_path = './data/BRCA1_shifted_test.fasta'
        change_fasta_start_pos('./data/BRCA1_one_line_test.fasta', 2,
                               'BRCA1_shifted')
        output_file_path = './BRCA1_shifted.fasta'

        self.assertTrue(os.path.exists(output_file_path))

        with open(output_file_path, 'r') as output_file:
            with open(test_file_path, 'r') as test_file:
                written_content = output_file.read()
                test_content = test_file.read()
                self.assertEqual(written_content, test_content)

    def test_select_genes_from_gbk_to_fasta_write_to_file(self):
        test_file_path = './data/example_gbk_selected_genes_test.fasta'
        select_genes_from_gbk_to_fasta('./data/example_gbk.gbk', 'pxpA')
        output_file_path = './example_gbk_selected_genes.fasta'

        self.assertTrue(os.path.exists(output_file_path))

        with open(output_file_path, 'r') as output_file:
            with open(test_file_path, 'r') as test_file:
                written_content = output_file.read()
                test_content = test_file.read()
                self.assertEqual(written_content, test_content)

    def tearDown(self):
        output_file_paths = ['./BRCA1_one_line.fasta', './BRCA1_shifted.fasta',
                             './example_gbk_selected_genes.fasta']
        for path in output_file_paths:
            if os.path.exists(path):
                os.remove(path)

if __name__ == '__main__':
    unittest.main()
